### ISSUE TITLE
New term: "homoscedasticity assumption"

### ISSUE THREAD

**Issue by cmaumet** [ISA-tools/stato#39]
Hello,

This proposal has been written up with @nicholst.

As suggested by @proccaserra in #28 (cf. [this comment](https://github.com/ISA-tools/stato/issues/28#issuecomment-65692051)), we were looking at re-using [stato:'homoscedasticity hypothesis'](http://purl.obolibrary.org/obo/STATO_0000054) in NIDM to specify whether the variance of the model is homogeneous or not (currently specified using the attribute [nidm:errorVarianceHomogeneous in a nidm:ErrorModel](http://nidm.nidash.org/specs/nidm-results_dev.html#dfn-nidm-errormodel)).

However the definition:
- [stato:'homoskedasticity hypothesis'](http://purl.obolibrary.org/obo/STATO_0000054): "homoscedasticity is a null hypothesis stating that all variances under consideration are homogenous"

seems to cover a different concept from the "homoscedasticity assumption" we would need.

To clarify, here is how we see 'hypotheses' and 'assumptions' relating to 'statistical models':
- In statistics, a _hypothesis_ is a statement about the population as a whole, often about specific parameters (see e.g. [wikipedia](http://en.wikipedia.org/wiki/Null_hypothesis#Basic_definitions)). A null _hypothesis_ is posed specifically for a statistical test, and may be rejected based on the outcome of the test.
- An _assumption_ is a facet of a _statistical model_; each _assumption_ is an elemental statement about the data generating mechanism, and often describes how that mechanism relates to (unobservable) parameters (see again [wikipedia](http://en.wikipedia.org/wiki/Statistical_model)). A _statistical model_ embodies _assumptions_; it is defined by and built-up out of its _assumptions_.

Note that a "Heteroscedasticity" as an assumption allows homoscedasticity as a possible state, while "Heteroscedasticity" as a hypothesis does not.

Do you think that we could create a new term in STATO for 'homoscedasticity assumption'? I would be happy to give it a go and write a pull request if you think that would be useful.

Thank you!

**Comment by proccaserra** [comment]
@nicholt @cmaumet this is quite an important point. We recycled a pattern we defined in OBI to create a number of subclasses to 'data transformation'. We kept talking about test X 'assuming' 'homogenous variance', so I believe we implied 'assumption'.  The main usages we had in mind are:
-capture the condition of application of a data transformation (a statistical test (which cover goodness of fit test)).
-compare parameters about the data and check against the condition of application of the test to detect possible conflicts.

we tried this with 'repeated measure anova', which can be subsumed in a model fitting.

My understanding is that we used hypothesis as model assumptions, but stick to hypothesis because the pattern was there. Adding assumptions would require working out exactly the differentia or alter the modelling. In fact, in our representation (and way of thinking), we did not consider that setting an axiom to state the hypothesis X should be true was excluding the actual data to be contradicting the hypothesis.

How would assumption work on an axiomatic level?

Many thanks!

**Comment by cmaumet** [comment]
@proccaserra: sorry for our late reply... 

As suggested, I just had a look at the 'reapeated measure ANOVA' where STATO defines:

```
'obo:has part' some ('obo:normal distribution hypothesis' and ('obo:has value' value true))
'obo:has part' some ('obo:sphericity hypothesis' and ('obo:has value' value true))
obo:achieves_planned_objective some 
  ('obo:within subject comparison objective' and 'obo:between group comparison objective')
```

For me this is saying that the 'repeated measure ANOVA' assumes a Gaussian distribution of the data and sphericity. While the 'achieves_planned_objective' is used to specify the alternative hypothesis.  

So, correct me if I am doing this wrong, but we could similarly have:
- 'two sample t-test with equal variance':

```
'obo:has part' some ('obo:normal distribution hypothesis' and ('obo:has value' value true))
'obo:has part' some ('obo:homoskedasticity hypothesis' and ('obo:has value' value true))
obo:achieves_planned_objective some 'obo:between group comparison objective'
```
- 'Levene's test':

```
obo:achieves_planned_objective some 'obo:equal variance testing objective'
```

From your answer we seem to be in agreement on the meaning of assumption (i.e. a "condition of application of a data transformation"). And looking at the above examples in STATO, it looks like the difference between "assumption" and "hypothesis" is taken into account by using either "obo:has part" (assumption) or "obo:achieves_planned_objective" (alternative hypothesis).

So maybe re-working the definition is all we need. Currently the 'homoskedasticity hypothesis' is defined as:
<i>
"homoskedasticity is a null hypothesis stating that all variances under consideration are homogenous."
</i>

If this term is to be used to specify assumptions (such as in the 'two sample t-test with equal variance' above), I think that we should avoid the use of "null hypothesis" in its definition as this can be misleading. (The null hypothesis of a 'two sample t-test with equal variance' is that the group means are equal.)

How would you feel about defining 'homoskedasticity' as:
<i>
"homoskedasticity states that all variances under consideration are homogenous."
</i>
?
