### ISSUE TITLE
Some STATO classes have unusual unresolvavle PURLs

### ISSUE THREAD

**Issue by cmungall** [ISA-tools/stato#40]
E.g
http://www.ontobee.org/browser/rdf.php?o=STATO&iri=http://purl.obolibrary.org/obo/stato.owl%23STATO_0000296

**Comment by agbeltran** [comment]
The URL was fixed in the development version of STATO to 
http://purl.obolibrary.org/obo/STATO_0000296

Release 1.2 contained the wrong URL:
http://purl.obolibrary.org/obo/stato.owl#STATO_0000296

However, this is resolving for me:
http://www.ontobee.org/browser/rdf.php?o=STATO&iri=http://purl.obolibrary.org/obo/stato.owl%23STATO_0000296
Is it not resolving for you?

Anyway, the URL will be fixed in release 1.3 and we will make sure we update to that version Ontobee and BioPortal.

Thanks

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/stato.owl#STATO_0000296 resolves to the complete OWL file which is suboptimal. Anyway glad to see it will be fixed (you don't need to explicitly update the version in OntoBee, it should pick it up automatically from the ontology purl)

**Comment by agbeltran** [comment]
Right, I got what you meant before now. Yes, this is already fixed in the development version and it will be live in the next release. Thanks for spotting the issue.

**Comment by agbeltran** [comment]
The fixes are now live in version 1.3.
