### ISSUE TITLE
machine learning terms

### ISSUE THREAD

**Issue by cmungall** [ISA-tools/stato#51]
It seems machine learning is out of scope for STATO? I don't see relevant classes.

What would a recommendation be for a compatible ontology?

**Comment by proccaserra** [comment]
what are the terms you need? how do you need them defined and placed in a semantic context?
send them along , we'll tell you, best.

**Comment by cmungall** [comment]
This was more of a drive-by request. Someone at my institute inquired about a taxonomy for machine learning. I'd like to recommend stato

I'm guessing something like this:
http://machinelearningmastery.com/a-tour-of-machine-learning-algorithms/

I don't think a detailed semantic axiomatization would be required.

**Comment by proccaserra** [comment]
scikit-learn has a nice diagram:
http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
and OBI, under the 'data transformation' branch has
http://bioportal.bioontology.org/ontologies/OBI/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0200000

should provide help. We did not to reinvent the wheel in STATO since we know it is in part covered by OBI.
