### ISSUE TITLE
 process is BFO_0000007 or BFO_0000015 ?

### ISSUE THREAD

**Issue by cfrancois7** [ISA-tools/stato#64]
I noted the process type is defined as BFO_0000007 in STATO but BFO_0000015 in BFO. In fact, BFO_0000007 doesn't exist anymore in the BFO 2.0, neither in the OBI last releases.
Is it not a problem to keep the two types with the same label ? It quite disturbing when we import the types from STATO.

Best regards,

See: https://github.com/obi-ontology/obi/issues/917#issuecomment-377972706

**Comment by agbeltran** [comment]
@cfrancois7 thanks for your report - could you please let us know what STATO version are you looking at? I couldn't confirm the problem you report. 

If you look at the STATO development version, there is no reference to BFO_0000007 or BFO_0000015 directly:

https://raw.githubusercontent.com/ISA-tools/stato/dev/dev/ontology/stato.owl

This is because we are importing these terms from OBI. If you look at the OBI import file here:

https://raw.githubusercontent.com/ISA-tools/stato/dev/dev/ontology/imports/obi_import.owl

you can see that there is no reference to BFO_0000007 and BFO_0000015 is indeed process.

See this line:
https://github.com/ISA-tools/stato/blob/8a87457a0e6600eb18ea8ce132a145b5067587ef/dev/ontology/imports/obi_import.owl#L1568

Maybe you were looking at another version and not the development one?

**Comment by proccaserra** [comment]
@cfrancois7 +1 thanks for your report. @agbeltran I believe @cfrancois7 uses our stato release via
 <owl:imports rdf:resource="http://purl.obolibrary.org/obo/stato.owl"/>, which has the issue mentioned and which I, too, ran into when working on the metabolomics applications.

@cfrancois7 we are about to make a new release but if the meantime, 

<owl:imports rdf:resource="https://raw.githubusercontent.com/ISA-tools/stato/dev/dev/ontology/stato.owl"/>  should solve your issue.

We'll update you when we release the new STATO version. 
Thx again.

**Comment by agbeltran** [comment]
yes, thanks @proccaserra - a new release is long overdue and the live version (from the PURL) is extremely outdated; I'm preparing the release and will close the issue when completed.

**Comment by cfrancois7** [comment]
@agbeltran As @proccaserra said, I'm using the PURL version.
Also, in the `dev` branch, in the `latest release` file, the [stato.owl](https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.owl) uses `BFO_0000007` as process. It seems to be the same version as the PURL one. I noted it was modified two years ago, so I understand the recent modifications weren't applied.

I'll switch to the current development version to solve my issue by waiting the new release. Thanks.

**Comment by proccaserra** [comment]
@cfrancois7 the stato file we work on before making a release can be found here:
https://github.com/ISA-tools/stato/tree/dev/dev/ontology/stato.owl

I think you were grabbing the file from the following:
https://github.com/ISA-tools/stato/tree/dev/releases/latest_release, which indeed contains the BFO_000007 issue.

Let us know if this fixes the issue. best.
