### ISSUE TITLE
Add 'Identity covariance structure'

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#69]
Hi,
please add 'Identity covariance structure' as a subclass of 'covariance structure' (STATO_0000346)

**Comment by proccaserra** [comment]
@hcwi can you provide a reference to reference / publication ?

**Comment by nicholst** [comment]
For what it's worth "Identity covariance structure" is the degenerate case of `no covariance structure'.  

SAS's PROC_MIXED, lists nearly every covariance structure I can think of:  
https://support.sas.com/documentation/cdl/en/statug/63347/HTML/default/viewer.htm#statug_mixed_sect020.htm#statug.mixed.randomstmt_type_un
but doesn't bother to mention "identity"

Closest is "Banded Main Diagonal" where all off-diagonals are zero but the diagonal is allowed to vary, while @hcwi is talking about the case where diagonal is constant.  (It is an usual case, because in many repeated measures designs if the covariance structure is 'identity' that variance component will be aliased with other variance parameters in the model (i.e. you can write the model down, but the parameter won't be estimable).

**Comment by hcwi** [comment]
As @nicholst has correctly spotted, by 'Identity' I am thinking of a (block) constant diagonal matrix. SAS's PROC_MIXED uses it as a default structure, named also VC:
> The REPEATED statement is used to specify the  matrix in the mixed model. (...) If no REPEATED statement is specified,  is assumed to be equal to (_sigma_^2)***I**.

The example of VC in Table 56.15 from the link above shows the diagonal matrix corresponding to identity covariance structure of two random effects (B and AB).


'Identity' covariance structure is also considered in MIXED procedure of SPSS:
https://www.ibm.com/support/knowledgecenter/en/SSLVMB_24.0.0/spss/advanced/covariance_structures.html
> Variance Components. This structure assigns a scaled identity (ID) structure to each of the specified random effects.

(see examples here: https://stats.idre.ucla.edu/spss/seminars/spss-mixed-command)

'Identity' is also the covariance structure used in R's lme4 package.


In fact, the name "Scaled Identity covariance structure" seems more explicit. Alternative name used in those packages, i.e. VC or Variance Component structure, is linked to the interpretation of its parameters _sigma_ as variance components of the model.
