### ISSUE TITLE
Estimator, estimate, estimate_of

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#74]
Hi, a suggestion to clean the terminology about estimation:

An _estimator_ (currently not in STATO, but an implicit superclass of _BLUE_, _BLUP_ and _eBLUP_) is an instruction (rule/formula, in STATO currently BLUE is a subclass of _data transformation_) to obtain an _estimate_ (some value or interval, e.g. _model parameter estimate_) being an _estimate_of_ (not _estimato_**r**__of_ !) some _parameter_ (_model parameter_)

Removing the 'r' from the property name would make some statisticians more happy about using it accoding to its definition.
Perhaps adding an Estimator class can also be considered.

**Comment by hcwi** [comment]
Additionally, I suggest that _statistic estimator_ should be removed. 

> A statistic is distinct from a statistical parameter, which is not computable, because often the population is too large to examine and measure all its items. However, a statistic, when used to estimate a population parameter, is called an estimate. For instance, the sample mean is a statistic that estimates the population mean, which is a parameter. (https://en.wikipedia.org/wiki/Statistic)

**Comment by nicholst** [comment]
+1 for @hcwi's suggestion:

> Additionally, I suggest that *statistic estimator* should be removed.
>

Statistic is something that is a function of the data alone (I.e. it
doesn't depend on unknowns, like parameters). There are different types of
statatics, as @hcwi mentions, point estimators, interval estimators, but
also test statistics and P-values.

-- 
_________________________________________________________
Thomas Nichols, PhD
Professor of Neuroimaging Statistics
Nuffield Department of Population Health | University of Oxford
Big Data Institute | Li Ka Shing Centre for Health Information and Discovery
Old Road Campus | Headington | Oxford | OX3 7LF | United Kingdom
T: +44 1865 743590 | E: thomas.nichols@bdi.ox.ac.uk
W: http://nisox.org | http://www.bdi.ox.ac.uk

**Comment by proccaserra** [comment]
@hcwi 
I see your point, I have changed the relation and set the domains and range (even though you'll probably find it restrictive, please consider this work in progress for this section). 
@hcwi @nicholst wrt 'statistical estimator' , this class is a placeholder used for prototyping/discussion.
( you can spot them via the incomplete class metadata). I was trying to capture the ideas we are discussing here but did not complete. great you are reviving the discussion. So are you asking for dropping 'statistical estimator' but create a Class 'estimator' estimator, parent for 'point estimator' , 'interval estimator', statistics , possibly placed under 'measurement datum' ?

When it comes to BLUE,BLUP, eBLUP, language use turns out to be extremely ambiguous with authors using the same words to talk about the data transformation *and* its output.

**Comment by nicholst** [comment]
@proccaserra Estimator certainly deserves to be a parent of 'point estimator' , 'interval estimator', and is clearer without "statistical" as a qualifier.

First, I want to point to two really useful and hopefully canonical-enough technical glossaries we can reference. (Wikipedia is good, but often just echoes confusion in the lay community).

Glossary from online textbook SticiGui by [Philip Stark](https://www.stat.berkeley.edu/~stark/index.html): https://www.stat.berkeley.edu/~stark/SticiGui/Text/gloss.htm 

[OECD Glossary of Statistical Terms](http://ec.europa.eu/eurostat/ramon/coded_files/OECD_glossary_stat_terms.pdf)

The second one is biased towards "official statistics" and not biomedical applications -- which we might assume STATO is oriented -- but I find is a useful canonical source.

So, both of these agree that "estimator" is a process, e.g. from OECD ([p265](http://ec.europa.eu/eurostat/ramon/coded_files/OECD_glossary_stat_terms.pdf#page=265)): "A rule or method of estimating a parameter of a population."

On "statistic" they also agree, though I like SticiGui's better: 
> A number that can be computed from data, involving no unknown parameters. As a function of a random sample, a statistic is a random variable. Statistics are used to estimate parameters, and to test hypotheses.

But there is a perhaps problem:  Not all statistics are estimators.  Estimators are a guess at a feature of the population, i.e. a population parameter.  The most widely used statistic, the sample mean, is such an estimator.  But a "test statistic", e.g. a T-score, doesn't estimate a population parameter... it is a measure of evidence against a null hypothesis, and all things equal, when there is an effect, with more and more data it grows larger and larger in magnitude.  Hence it can't be considered an estimator.

On your last point...
> When it comes to BLUE,BLUP, eBLUP, language use turns out to be extremely ambiguous with authors using the same words to talk about the data transformation and its output.

Unfortunately neither glossary covers BLUE/BLUP/eBLUP.   I'll simply offer my take:

* **BLUE** - A characteristic of an estimator of fixed effects (constants, a particular number determined by the population). The characteristic can only be assured/determined by reference to assumptions on the distribution sampled and asserted "in theory".  For one particular instance of an estimate, the description "BLUE" is asserting that the estimator is known to be BLUE under a certain set of assumptions.

* **BLUP** - A characteristic of an estimator of random effects (random variables arising from individual consistent members of a population), usually referred to as predictor.  Again, can only be assured/determined by reference to assumptions on the distribution of population sampled. For a particular estimate/prediction, the name "BLUP" is asserting that the estimator/predictor method has the BLUP characteristic.  

* **eBLUP** - The form that all BLUP's take in practice.  BLUPs are functions of unknown (variance) parameters of the population, and so to compute one in practice the unknown values are replaced with estimates, for which some authors are careful to describe as "emperical BLUPs".

Most of Normal-theory, independent observation statistical methods are BLUE.  So much so that we usually don't mention it.  As random effects are less common, to make the distinction clear between estimating fixed effects and estimating/predicting random effects, the "BLUP" moniker is applied.  But every practical application where "BLUPs" are used they are really "eBLUPs".  So you either declare that most of the literature citing "BLUPs" are wrong, or you take (what is a commonly received notion) that users of BLUPs know that they are actually eBLUPs, and so eBLUP is an alias for BLUP.

Hope this helps advance the discussion!

**Comment by hcwi** [comment]
Thank you @nicholst for your contribution and the definitions. 
@proccaserra, I strongly support the above suggestion to skip 'statistic(al)' from the estimator name:
> Estimator certainly deserves to be a parent of 'point estimator' , 'interval estimator', and is clearer without "statistical" as a qualifier.

and to remove the property 'estimate of some statistic' from its definiton. As mentioned, a statistic can only be calculated, not estimated. When a statistic is calculated according to an estimator's formula, it can constitute an 'estimate' from the estimator (see below).


When it comes to the ambiguous language, the confusion results indeed from common using of the word 'estimator' to describe two things: both the process and its result (estimated value of a parameter). In many cases the distinction doesn't matter or it is clear from the context what is meant. 
But the common practice of sharing the names should not be reflected in the ontology, imo, if we want to help clarify the definitions and reduce the confusion!

'Estimator' is primarily a process, as @nicholst stated above. It can be characterised by a _formula_ and some properties (like being linear, consistent, unbiased or empirical). Some estimators of particularly useful properties are specifically named -> hence the subtypes of estimators: BLUE, BLUP, eBLUP.

The output of the estimation, i.e. 'realisation of the estimator' or simply its value, is called an 'estimate'. The name has already been used in STATO (to label specific estimates, e.g. contrast estimate, effect size estimate, etc. or the property 'estimate of') so for consistency I'd suggest keeping this convention. Perhaps an 'Estimate' superclass can be considered for them.
How to call the realisation (output) of BLUE, BLUP, and eBLUP processes then? Careful authors write simply 'BLUE estimate' or 'BLUP estimate', which is explicit and clear. Others sometimes use BLUE**s** or BLUP**s** to indicate they mean the values, and not the rule to calculate them.

**Comment by nicholst** [comment]
Agree with all of @hcwi’s comment. 

Just one typo. I think @hcwi meant  to write:

> Some estimators *possessing* particularly useful properties are specifically named -> hence the subtypes of estimators: BLUE, BLUP, eBLUP.

with correction in *italics*.
