### ISSUE TITLE
Non-integer degrees of freedom

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#77]
Hi,
A minor remark: the number of degrees of freedom doesn't need to be an integer! especially, when they are calculated with df approximation methods.

**Comment by agbeltran** [comment]
Thanks @hcwi - I changed the super class for 'number of degrees of freedom' to be 'measurement datum' instead of 'count' (that restricted it to be an integer) and added some notes to refer to this issue and some online info about non-integer degrees of freedom. Closing now. Please re-open if anything else is missing. Thanks!
